name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && success() }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: |
          chmod +x zapakiraj_27116.sh
          ./zapakiraj_27116.sh $DOCKER_USERNAME $DOCKER_PASSWORD $REPO_NAME

      - name: Run Docker Container
        run: |
          chmod +x zazeni_27116.sh
          ./zazeni_27116.sh
