name: Testiranje

on:
  push:
    branches:
      - main

jobs:
  check_tests:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Preveri
        run: |
          if [ -f konvolucija_test.py ]; then
            echo "Napaka: Testne skripte ni mogoče najti" > napaka.txt
            exit 1
          fi

      - name: Naloži artefakt napake
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: napaka
          path: konvolucija_test.py

  run_tests:
    runs-on: self-hosted
    needs: check_tests
    strategy:
      matrix:
        python-version: [3.11.2, 3.11.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prenesi artefakte
        uses: actions/download-artifact@v2
        with:
          name: napaka
          path: artifacts/konvolucija_test.py 
      
      
      - name: Preveri napake
        run: |
          if [ -e napaka.txt ]; then
            echo "Odkrita napaka, prenehanje nadaljnjih procesov"
            exit 1
          fi

      - name: Nastavi Python okolje
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Zaženi teste
        run: |
          pytest konvolucija_test.py

      
