name: Testiranje

on:
  push:
    branches:
      - main

jobs:
  check_tests:
    runs-on: self-hosted
    steps:
      - name: Preveri
        run: |
          if [ ! -f konvolucija_test.py ]; then
            echo "Testne skripte najdene"
          else
            echo "Napaka: Testne skripte ni mogoče najti" > napaka.txt
            exit 1
          fi
        continue-on-error: true

      - name: Naloži artefakt napake
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: error-artifact
          path: napaka.txt

  run_tests:
    runs-on: self-hosted
    needs: check_tests
    strategy:
      matrix:
        python-version: [3.6.7, 3.7.2]
    steps:
      - name: Nastavi Python okolje
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Zaženi teste
        run: |
          pytest konvolucija_test.py
        continue-on-error: true

      - name: Preveri napake
        run: |
          if [ -e napaka.txt ]; then
            echo "Odkrita napaka, prenehanje nadaljnjih procesov"
            exit 1
          fi
