name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_to_dockerhub:
    runs-on: self-hosted
    needs: testiranje
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-docker-image:latest .
        working-directory: ${{ github.workspace }}

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push my-docker-image:latest

  testiranje:
    runs-on: self-hosted
    steps:
      - name: Check if test scripts exist
        run: |
          if [ -e tests/konvolucija_test.py ]; then
            echo "Test scripts found"
          else
            echo "Error: Test scripts not found" > napaka.txt
            exit 1
          fi
        continue-on-error: true

      - name: Upload error artifact
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: error-artifact
          path: napaka.txt

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          pytest tests/konvolucija_test.py
        continue-on-error: true

      - name: Check for errors
        run: |
          if [ -e napaka.txt ]; then
            echo "Error detected, stopping further processes"
            exit 1
          fi
