name: Testiranje

on:
  push:
    branches:
      - main

jobs:
  check_tests:
    runs-on: self-hosted
    steps:
      - name: Check if test scripts exist
        run: |
          if [ -e tests/konvolucija_test.py ]; then
            echo "Test scripts found"
          else
            echo "Error: Test scripts not found" > napaka.txt
            exit 1
          fi
        continue-on-error: true

      - name: Upload error artifact
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: error-artifact
          path: napaka.txt

  run_tests:
    runs-on: self-hosted
    needs: check_tests
    strategy:
      matrix:
        python-version: [3.6.7, 3.6.12, 3.7.2, 3.7.4]
    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          pytest tests/konvolucija_test.py
        continue-on-error: true

      - name: Check for errors
        run: |
          if [ -e napaka.txt ]; then
            echo "Error detected, stopping further processes"
            exit 1
          fi
