name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && success() }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build and Push Docker Image
        run: |
          chmod +x zapakiraj_27116.sh
          ./zapakiraj_27116.sh

      - name: Run Docker Container
        run: |
          chmod +x zapakiraj_27116.sh
          ./zazeni_27116.sh
